In [1]:
import numpy as np
from numpy.linalg import det, pinv, matrix_rank, norm
from mdputils import *

In [2]:
# Test matrices
# Recurrent but periodic
P1 = np.array([[0.0, 1, 0], [0, 0, 1], [1, 0, 0]]) 
# Reducible
R1 = np.eye(3)
# Ergodic
E1 = np.array([[0.5, 0.5],[0.1, 0.9]])
E2 = np.array([[0.2, 0.4, 0.4], [0.2, 0, 0.8], [0.2, 0.0, 0.8]])
# Absorbing
A1 = np.array([[0.2, 0.4, 0.4], [0.5, 0, 0.5], [0, 0, 1]])

tstmat = [P1, R1, E1, E2, A1]

In [3]:
P = np.array([[0.5, 0.5], [0.1, 0.9]])

sa = approx_stationary(P)
se = stationary(P)

print(sa)
print(se)

[ 0.1666689  0.8333311]
[ 0.16666667  0.83333333]


A random MP should be, if possible, ergodic

A random MDP should have, if possible, significant differences according to the policy applied to it. It would be even nicer if the differences were in some sense tunable.

In [21]:
for i in tstmat:
    print(is_reducible(i))

False
True
False
False
True


In [35]:
T = transition_matrix(3)
print(T)
print('*'*30)
print("Stochastic?:", is_stochastic(T))
print("Absorbing?:", is_absorbing(T))
print("Periodic?:", is_periodic(T))
print("Reducible?:", is_reducible(T))
print("Recurrent?:", is_recurrent(T))
print("Ergodic?:", is_ergodic(T))

[[ 0.23010326  0.34568871  0.42420803]
 [ 0.40827089  0.33455106  0.25717804]
 [ 0.37149958  0.56139231  0.06710811]]
******************************
Stochastic?: True
Absorbing?: False
Periodic?: False
Reducible?: False
Recurrent?: True
Ergodic?: True
