In [1]:
import numpy as np

In [18]:
def find_limit(P, tol=1e-6, limit=1000):
    Q = np.copy(P)
    Q = np.dot(Q, P)
    count = 0
    while np.sum(np.abs(Q - P)) > tol and count < limit:
        Q = np.dot(Q, P)
        count += 1
    return Q

In [19]:
p = 1/2
q = 1/4

pm = [[p, 1-q], [1-p, q]]
pm = np.array(pm)

In [20]:
qm = find_limit(pm)

In [21]:
np.dot(pm, qm)

array([[ 0.6,  0.6],
       [ 0.4,  0.4]])

In [32]:
fp = (pm - np.eye(2))
fp[:,-1] = 1

f0 = np.zeros((2,2))
f0[:,-1] = 1

In [35]:
fpinv = np.linalg.pinv(fp)

In [36]:
np.dot(f0, fpinv)

array([[ 0.5,  0.5],
       [ 0.5,  0.5]])

In [39]:
np.dot(np.ones((2,2))/2, pm)

array([[ 0.5,  0.5],
       [ 0.5,  0.5]])

In [48]:
aa = np.ones(2)
aa = aa/np.sum(aa)
np.dot(aa, pm)

array([ 0.5,  0.5])

In [51]:
np.linalg.eig(qm)

(array([ 1.,  0.]), array([[ 0.83205029, -0.70710678],
        [ 0.5547002 ,  0.70710678]]))

In [60]:
# random initial choice
s0 = np.random.random(2)
s0 = s0/np.sum(s0)
s = np.copy(s0)

# use equal distribution
s = np.ones(2)/2
for i in range(1000):
    s = np.dot(pm, s)
print(s)

[ 0.6  0.4]


In [61]:
np.dot(pm, aa)

array([ 0.625,  0.375])

In [62]:
pm

array([[ 0.5 ,  0.75],
       [ 0.5 ,  0.25]])

In [63]:
# OK, so numpy is doing something weird with ordering

In [65]:
np.dot([0.1, 0.9], pm)

array([ 0.5,  0.3])